import type { SectionDef } from "./ui";

export const SECTIONS: SectionDef[] = [
  {
    id: "motion",
    title: "Motion & Acceleration",
    desc: "DeviceMotion — accelerometer, gyroscope, activity",
    gateLabel: "iOS requires a tap to grant motion-sensor access.",
    toggleable: true,
    cards: [
      {
        id: "accel",
        icon: "\u{1F4E1}",
        title: "Accelerometer",
        sparkline: true,
        triaxis: true,
        fields: [
          { key: "x", label: "X", unit: "m/s²" },
          { key: "y", label: "Y", unit: "m/s²" },
          { key: "z", label: "Z", unit: "m/s²" },
          { key: "mag", label: "Magnitude", unit: "m/s²" },
        ],
        note: "Includes gravity, matching Android's raw TYPE_ACCELEROMETER.",
      },
      {
        id: "linaccel",
        icon: "➤",
        title: "Linear Acceleration",
        triaxis: true,
        fields: [
          { key: "x", label: "X", unit: "m/s²" },
          { key: "y", label: "Y", unit: "m/s²" },
          { key: "z", label: "Z", unit: "m/s²" },
        ],
        note: "Gravity removed by the OS, when the browser reports it.",
      },
      {
        id: "gravity",
        icon: "\u{1FA90}",
        title: "Gravity",
        triaxis: true,
        fields: [
          { key: "x", label: "X", unit: "m/s²" },
          { key: "y", label: "Y", unit: "m/s²" },
          { key: "z", label: "Z", unit: "m/s²" },
        ],
        note: "Estimated: exact acceleration minus linear acceleration, or a low-pass filter as fallback.",
      },
      {
        id: "gyro",
        icon: "\u{1F300}",
        title: "Gyroscope",
        sparkline: true,
        triaxis: true,
        fields: [
          { key: "x", label: "α (Z)", unit: "°/s" },
          { key: "y", label: "β (X)", unit: "°/s" },
          { key: "z", label: "γ (Y)", unit: "°/s" },
        ],
      },
      {
        id: "activity",
        icon: "\u{1F3C3}",
        title: "Activity Detector",
        stateViz: true,
        fields: [
          { key: "state", label: "State" },
          { key: "variance", label: "Motion energy" },
        ],
        note: "Derived from accelerometer variance — approximates Significant/Stationary/Motion Detect.",
      },
      {
        id: "steps",
        icon: "\u{1F45F}",
        title: "Step Counter",
        gauge: true,
        fields: [
          { key: "count", label: "Steps" },
          { key: "cadence", label: "Last minute" },
        ],
        note: "Estimated: peak-detection over the accelerometer signal — approximates Step Counter/Step Detector, not hardware-pedometer accuracy.",
      },
      {
        id: "motion-na",
        icon: "\u{1F6AB}",
        title: "Not exposed by browsers",
        note: "Accelerometer (Uncalibrated) and Gyroscope (Uncalibrated) have no Web API — they require raw OS sensor-fusion access browsers intentionally don't expose. Hinge Angle has no direct equivalent either, but see Device Posture in Device & System for the closest thing (fold state, not the angle).",
      },
    ],
  },
  {
    id: "orientation",
    title: "Orientation & Compass",
    desc: "DeviceOrientation & Generic Sensor API",
    gateLabel: "iOS requires a tap to grant orientation-sensor access.",
    toggleable: true,
    cards: [
      {
        id: "compass",
        icon: "\u{1F9ED}",
        title: "Compass Heading",
        compass: true,
        fields: [
          { key: "heading", label: "Heading", unit: "°" },
          { key: "ref", label: "Reference" },
        ],
      },
      {
        id: "attitude",
        icon: "⚖️",
        title: "Attitude & Tilt",
        level: true,
        fields: [
          { key: "beta", label: "Pitch (β)", unit: "°" },
          { key: "gamma", label: "Roll (γ)", unit: "°" },
        ],
        note: "Approximates ROTATION_VECTOR / TILT_DETECTOR from orientation angles.",
      },
      {
        id: "magneto",
        icon: "\u{1F9F2}",
        title: "Magnetic Field",
        triaxis: true,
        fields: [
          { key: "x", label: "X", unit: "µT" },
          { key: "y", label: "Y", unit: "µT" },
          { key: "z", label: "Z", unit: "µT" },
        ],
        note: "Generic Sensor API — supported only on Chrome/Edge for Android, over HTTPS.",
      },
      {
        id: "screenorient",
        icon: "\u{1F4F1}",
        title: "Screen Orientation",
        rotateIcon: true,
        fields: [
          { key: "angle", label: "Angle", unit: "°" },
          { key: "type", label: "Type" },
        ],
      },
      {
        id: "orient-na",
        icon: "\u{1F6AB}",
        title: "Not exposed by browsers",
        note: "Magnetic Field (Uncalibrated), Geomagnetic Rotation Vector and Game Rotation Vector aren't separately available — the browser only ever exposes one fused orientation reading.",
      },
    ],
  },
  {
    id: "environment",
    title: "Environment & Location",
    desc: "Geolocation, ambient light, microphone",
    toggleable: true,
    cards: [
      {
        id: "gps",
        icon: "\u{1F4CD}",
        title: "GPS Location",
        gpsSignal: true,
        fields: [
          { key: "lat", label: "Latitude", unit: "°" },
          { key: "lon", label: "Longitude", unit: "°" },
          { key: "alt", label: "Altitude", unit: "m" },
          { key: "speed", label: "Speed", unit: "m/s" },
          { key: "heading", label: "Heading", unit: "°" },
          { key: "acc", label: "Accuracy", unit: "m" },
        ],
      },
      {
        id: "trip",
        icon: "\u{1F6E3}️",
        title: "Trip Computer",
        sparkline: true,
        gauge: true,
        fields: [
          { key: "distance", label: "Distance", unit: "km" },
          { key: "speed", label: "Speed", unit: "km/h" },
          { key: "avgspeed", label: "Avg speed", unit: "km/h" },
          { key: "maxspeed", label: "Max speed", unit: "km/h" },
          { key: "duration", label: "Duration" },
        ],
        note: "Distance and speed traveled, accumulated from consecutive GPS fixes (Haversine distance). Shares the GPS Location permission above.",
      },
      {
        id: "light",
        icon: "☀️",
        title: "Ambient Light",
        sparkline: true,
        gauge: true,
        fields: [{ key: "lux", label: "Illuminance", unit: "lux" }],
        note: "Generic Sensor API — removed from most browsers over fingerprinting concerns; rarely available.",
      },
      {
        id: "sound",
        icon: "\u{1F3A4}",
        title: "Sound Level",
        meter: true,
        sparkline: true,
        fields: [{ key: "db", label: "Level (relative)", unit: "dB" }],
        note: "Uncalibrated estimate from the microphone input, like the Android app's meter.",
      },
      {
        id: "heartrate",
        icon: "\u{1F493}",
        title: "Heart Rate",
        pulse: true,
        fields: [
          { key: "bpm", label: "BPM" },
          { key: "device", label: "Device" },
        ],
        note: "Pairs with an external Bluetooth heart-rate strap (standard GATT service). Chrome/Edge only — Web Bluetooth isn't available in Safari or Firefox.",
      },
      {
        id: "env-na",
        icon: "\u{1F6AB}",
        title: "Not exposed by browsers",
        note: "Barometric Pressure, Relative Humidity, Ambient Temperature and Proximity all need dedicated hardware access no Web API provides.",
      },
    ],
  },
  {
    id: "device",
    title: "Device & System",
    desc: "No permission required",
    cards: [
      {
        id: "cpu",
        icon: "\u{1F5A5}️",
        title: "Processor & Memory",
        fields: [
          { key: "cores", label: "Logical cores" },
          { key: "mem", label: "Device memory", unit: "GB" },
        ],
      },
      {
        id: "battery",
        icon: "\u{1F50B}",
        title: "Battery",
        meter: true,
        fields: [
          { key: "level", label: "Level" },
          { key: "charging", label: "Charging" },
          { key: "time", label: "Time remaining" },
        ],
        note: "The Battery Status API is deprecated and removed from most desktop browsers.",
      },
      {
        id: "cpupressure",
        icon: "\u{1F321}️",
        title: "CPU Pressure",
        fields: [{ key: "state", label: "State" }],
        note: "Compute Pressure API — load-derived pressure state (nominal/fair/serious/critical), the closest browser equivalent to the app's thermal-zone monitoring. Chrome/Edge only, experimental.",
      },
      {
        id: "network",
        icon: "\u{1F4F6}",
        title: "Network",
        fields: [
          { key: "status", label: "Status" },
          { key: "type", label: "Effective type" },
          { key: "downlink", label: "Downlink", unit: "Mb/s" },
          { key: "rtt", label: "Round-trip", unit: "ms" },
        ],
      },
      {
        id: "storage",
        icon: "\u{1F4BE}",
        title: "Storage",
        fields: [
          { key: "usage", label: "Used" },
          { key: "quota", label: "Quota" },
        ],
      },
      {
        id: "display",
        icon: "\u{1F5BC}️",
        title: "Display",
        fields: [
          { key: "res", label: "Resolution" },
          { key: "dpr", label: "Pixel ratio" },
          { key: "color", label: "Color depth", unit: "bit" },
        ],
      },
      {
        id: "platform",
        icon: "\u{1F310}",
        title: "Browser & Platform",
        fields: [
          { key: "browser", label: "Browser" },
          { key: "os", label: "Platform" },
          { key: "lang", label: "Language" },
          { key: "tz", label: "Time zone" },
        ],
      },
      {
        id: "input",
        icon: "✋",
        title: "Input",
        fields: [
          { key: "touch", label: "Touch points" },
          { key: "pointer", label: "Primary pointer" },
        ],
      },
      {
        id: "biometric",
        icon: "\u{1F446}",
        title: "Biometric Hardware",
        fields: [{ key: "available", label: "Platform authenticator" }],
        note: "Checks for Face ID / Touch ID / Windows Hello / fingerprint hardware via WebAuthn — matches the app's Hardware tab biometric check. Doesn't trigger authentication.",
      },
      {
        id: "posture",
        icon: "\u{1F4D2}",
        title: "Device Posture",
        fields: [{ key: "type", label: "Posture" }],
        note: "Device Posture API — reports folded/continuous state on foldable phones. Chrome/Android on supported foldables only.",
      },
    ],
  },
];
