import type { SectionDef } from "../render";

export const environmentSection: SectionDef = {
  id: "environment",
  title: "Environment & Location",
  desc: "Geolocation, ambient light, microphone",
  toggleable: true,
  cards: [
    {
      id: "gps",
      icon: "\u{1F4CD}",
      title: "GPS Location",
      gpsSignal: true,
      trail: true,
      fields: [
        { key: "lat", label: "Latitude", unit: "°" },
        { key: "lon", label: "Longitude", unit: "°" },
        { key: "alt", label: "Altitude", unit: "m" },
        { key: "speed", label: "Speed", unit: "m/s" },
        { key: "heading", label: "Heading", unit: "°" },
        { key: "acc", label: "Accuracy", unit: "m" },
      ],
      note: "The trail below plots recent fixes to scale — drawn locally, no map tiles are fetched from anywhere.",
    },
    {
      id: "trip",
      icon: "\u{1F6E3}️",
      title: "Trip Computer",
      sparkline: true,
      gauge: true,
      fields: [
        { key: "distance", label: "Distance", unit: "km" },
        { key: "speed", label: "Speed", unit: "km/h" },
        { key: "avgspeed", label: "Avg speed", unit: "km/h" },
        { key: "maxspeed", label: "Max speed", unit: "km/h" },
        { key: "duration", label: "Duration" },
      ],
      note: "Distance and speed traveled, accumulated from consecutive GPS fixes (Haversine distance). Shares the GPS Location permission above.",
    },
    {
      id: "light",
      icon: "☀️",
      title: "Ambient Light",
      sparkline: true,
      gauge: true,
      fields: [{ key: "lux", label: "Illuminance", unit: "lux" }],
      note: "Generic Sensor API — removed from most browsers over fingerprinting concerns; rarely available.",
    },
    {
      id: "proximity",
      icon: "\u{1F4CF}",
      title: "Proximity",
      stateViz: true,
      fields: [{ key: "distance", label: "Distance", unit: "cm" }],
      note: "Generic Sensor API's ProximitySensor — not implemented in any shipping browser yet, kept here for when it lands.",
    },
    {
      id: "sound",
      icon: "\u{1F3A4}",
      title: "Sound Level",
      meter: true,
      sparkline: true,
      fields: [{ key: "db", label: "Level (relative)", unit: "dB" }],
      note: "Uncalibrated estimate from the microphone input, like the Android app's meter.",
    },
    {
      id: "heartrate",
      icon: "\u{1F493}",
      title: "Heart Rate",
      pulse: true,
      fields: [
        { key: "bpm", label: "BPM" },
        { key: "device", label: "Device" },
      ],
      note: "Pairs with an external Bluetooth heart-rate strap (standard GATT service). Chrome/Edge only — Web Bluetooth isn't available in Safari or Firefox.",
    },
    {
      id: "env-na",
      icon: "\u{1F6AB}",
      title: "Not exposed by browsers",
      note: "Barometric Pressure, Relative Humidity and Ambient Temperature all need dedicated hardware access no Web API provides.",
    },
  ],
};
